// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: datasource/entity.proto

package datasource

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Resource with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Resource) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Resource with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ResourceMultiError, or nil
// if none found.
func (m *Resource) ValidateAll() error {
	return m.validate(true)
}

func (m *Resource) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ResourceId

	// no validation rules for ResourceName

	// no validation rules for ShortName

	// no validation rules for CloudType

	// no validation rules for CloudId

	// no validation rules for Service

	// no validation rules for Region

	// no validation rules for Layer

	// no validation rules for MetaData

	if len(errors) > 0 {
		return ResourceMultiError(errors)
	}

	return nil
}

// ResourceMultiError is an error wrapping multiple validation errors returned
// by Resource.ValidateAll() if the designated constraints aren't met.
type ResourceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResourceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResourceMultiError) AllErrors() []error { return m }

// ResourceValidationError is the validation error returned by
// Resource.Validate if the designated constraints aren't met.
type ResourceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceValidationError) ErrorName() string { return "ResourceValidationError" }

// Error satisfies the builtin error interface
func (e ResourceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResource.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceValidationError{}

// Validate checks the field values on ResourceRelationship with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResourceRelationship) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResourceRelationship with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResourceRelationshipMultiError, or nil if none found.
func (m *ResourceRelationship) ValidateAll() error {
	return m.validate(true)
}

func (m *ResourceRelationship) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RelationId

	// no validation rules for RelationLabel

	// no validation rules for SourceResourceName

	// no validation rules for TargetResourceName

	if len(errors) > 0 {
		return ResourceRelationshipMultiError(errors)
	}

	return nil
}

// ResourceRelationshipMultiError is an error wrapping multiple validation
// errors returned by ResourceRelationship.ValidateAll() if the designated
// constraints aren't met.
type ResourceRelationshipMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResourceRelationshipMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResourceRelationshipMultiError) AllErrors() []error { return m }

// ResourceRelationshipValidationError is the validation error returned by
// ResourceRelationship.Validate if the designated constraints aren't met.
type ResourceRelationshipValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceRelationshipValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceRelationshipValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceRelationshipValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceRelationshipValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceRelationshipValidationError) ErrorName() string {
	return "ResourceRelationshipValidationError"
}

// Error satisfies the builtin error interface
func (e ResourceRelationshipValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResourceRelationship.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceRelationshipValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceRelationshipValidationError{}
