// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	remediation "github.com/ca-risken/datasource-api/proto/remediation"
	mock "github.com/stretchr/testify/mock"
)

// RemediationServiceServer is an autogenerated mock type for the RemediationServiceServer type
type RemediationServiceServer struct {
	mock.Mock
}

// GenerateRemediationProposal provides a mock function with given fields: _a0, _a1
func (_m *RemediationServiceServer) GenerateRemediationProposal(_a0 context.Context, _a1 *remediation.GenerateRemediationProposalRequest) (*remediation.GenerateRemediationProposalResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRemediationProposal")
	}

	var r0 *remediation.GenerateRemediationProposalResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *remediation.GenerateRemediationProposalRequest) (*remediation.GenerateRemediationProposalResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *remediation.GenerateRemediationProposalRequest) *remediation.GenerateRemediationProposalResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*remediation.GenerateRemediationProposalResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *remediation.GenerateRemediationProposalRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRemediationServiceServer creates a new instance of RemediationServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemediationServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemediationServiceServer {
	mock := &RemediationServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
