// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ai/service.proto

package ai

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on InvokeAIRemediationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *InvokeAIRemediationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InvokeAIRemediationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// InvokeAIRemediationRequestMultiError, or nil if none found.
func (m *InvokeAIRemediationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *InvokeAIRemediationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetProjectId() <= 0 {
		err := InvokeAIRemediationRequestValidationError{
			field:  "ProjectId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetFindingId() <= 0 {
		err := InvokeAIRemediationRequestValidationError{
			field:  "FindingId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return InvokeAIRemediationRequestMultiError(errors)
	}

	return nil
}

// InvokeAIRemediationRequestMultiError is an error wrapping multiple
// validation errors returned by InvokeAIRemediationRequest.ValidateAll() if
// the designated constraints aren't met.
type InvokeAIRemediationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InvokeAIRemediationRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InvokeAIRemediationRequestMultiError) AllErrors() []error { return m }

// InvokeAIRemediationRequestValidationError is the validation error returned
// by InvokeAIRemediationRequest.Validate if the designated constraints aren't met.
type InvokeAIRemediationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InvokeAIRemediationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InvokeAIRemediationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InvokeAIRemediationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InvokeAIRemediationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InvokeAIRemediationRequestValidationError) ErrorName() string {
	return "InvokeAIRemediationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e InvokeAIRemediationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInvokeAIRemediationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InvokeAIRemediationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InvokeAIRemediationRequestValidationError{}

// Validate checks the field values on InvokeAIRemediationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *InvokeAIRemediationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InvokeAIRemediationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// InvokeAIRemediationResponseMultiError, or nil if none found.
func (m *InvokeAIRemediationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *InvokeAIRemediationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RemediationProposalId

	if len(errors) > 0 {
		return InvokeAIRemediationResponseMultiError(errors)
	}

	return nil
}

// InvokeAIRemediationResponseMultiError is an error wrapping multiple
// validation errors returned by InvokeAIRemediationResponse.ValidateAll() if
// the designated constraints aren't met.
type InvokeAIRemediationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InvokeAIRemediationResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InvokeAIRemediationResponseMultiError) AllErrors() []error { return m }

// InvokeAIRemediationResponseValidationError is the validation error returned
// by InvokeAIRemediationResponse.Validate if the designated constraints
// aren't met.
type InvokeAIRemediationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InvokeAIRemediationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InvokeAIRemediationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InvokeAIRemediationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InvokeAIRemediationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InvokeAIRemediationResponseValidationError) ErrorName() string {
	return "InvokeAIRemediationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e InvokeAIRemediationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInvokeAIRemediationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InvokeAIRemediationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InvokeAIRemediationResponseValidationError{}
