// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ai/service.proto

package ai

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GenerateRemediationProposalRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GenerateRemediationProposalRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenerateRemediationProposalRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// GenerateRemediationProposalRequestMultiError, or nil if none found.
func (m *GenerateRemediationProposalRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GenerateRemediationProposalRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetProjectId() <= 0 {
		err := GenerateRemediationProposalRequestValidationError{
			field:  "ProjectId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetFindingId() <= 0 {
		err := GenerateRemediationProposalRequestValidationError{
			field:  "FindingId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GenerateRemediationProposalRequestMultiError(errors)
	}

	return nil
}

// GenerateRemediationProposalRequestMultiError is an error wrapping multiple
// validation errors returned by
// GenerateRemediationProposalRequest.ValidateAll() if the designated
// constraints aren't met.
type GenerateRemediationProposalRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenerateRemediationProposalRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenerateRemediationProposalRequestMultiError) AllErrors() []error { return m }

// GenerateRemediationProposalRequestValidationError is the validation error
// returned by GenerateRemediationProposalRequest.Validate if the designated
// constraints aren't met.
type GenerateRemediationProposalRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenerateRemediationProposalRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenerateRemediationProposalRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenerateRemediationProposalRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenerateRemediationProposalRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenerateRemediationProposalRequestValidationError) ErrorName() string {
	return "GenerateRemediationProposalRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GenerateRemediationProposalRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenerateRemediationProposalRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenerateRemediationProposalRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenerateRemediationProposalRequestValidationError{}

// Validate checks the field values on GenerateRemediationProposalResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GenerateRemediationProposalResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenerateRemediationProposalResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// GenerateRemediationProposalResponseMultiError, or nil if none found.
func (m *GenerateRemediationProposalResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GenerateRemediationProposalResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RemediationProposalId

	if len(errors) > 0 {
		return GenerateRemediationProposalResponseMultiError(errors)
	}

	return nil
}

// GenerateRemediationProposalResponseMultiError is an error wrapping multiple
// validation errors returned by
// GenerateRemediationProposalResponse.ValidateAll() if the designated
// constraints aren't met.
type GenerateRemediationProposalResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenerateRemediationProposalResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenerateRemediationProposalResponseMultiError) AllErrors() []error { return m }

// GenerateRemediationProposalResponseValidationError is the validation error
// returned by GenerateRemediationProposalResponse.Validate if the designated
// constraints aren't met.
type GenerateRemediationProposalResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenerateRemediationProposalResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenerateRemediationProposalResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenerateRemediationProposalResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenerateRemediationProposalResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenerateRemediationProposalResponseValidationError) ErrorName() string {
	return "GenerateRemediationProposalResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GenerateRemediationProposalResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenerateRemediationProposalResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenerateRemediationProposalResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenerateRemediationProposalResponseValidationError{}
