// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AzureServiceClient is an autogenerated mock type for the AzureServiceClient type
type AzureServiceClient struct {
	mock.Mock
}

// VerifyCode provides a mock function with given fields: ctx, subscriptionID, verificationCode
func (_m *AzureServiceClient) VerifyCode(ctx context.Context, subscriptionID string, verificationCode string) (bool, error) {
	ret := _m.Called(ctx, subscriptionID, verificationCode)

	if len(ret) == 0 {
		panic("no return value specified for VerifyCode")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, subscriptionID, verificationCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, subscriptionID, verificationCode)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, subscriptionID, verificationCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAzureServiceClient creates a new instance of AzureServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAzureServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AzureServiceClient {
	mock := &AzureServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
